---
- name: Configure a AWX Server 7.0.0
  hosts: awxserver
  become: True
  vars:

  tasks:
    
#    - name: upgrade all packages
#      yum: name=* state=latest
        
    - name: install python tools
      yum: name=policycoreutils-python update_cache=yes
    
    - name: Open ports 8050-8052 to allow a webserver to listen
      seport:
        ports: 8050-8052
        proto: tcp
        setype: http_port_t
        state: present

    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
         
    - name: Install epel-release package
      yum: name=epel-release
      
    - name: Install centos utilities & wget
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - centos-release-scl
        - centos-release-scl-rh
        - wget

    - name: Add AWX repository
      yum_repository:
        name: copr:copr.fedorainfracloud.org:mrmeee:ansible-awx
        file: ansible-awx
        description: Copr repo for ansible-awx owned by mrmeee
        baseurl: https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/epel-7-$basearch/
#        type: rpm-md
        skip_if_unavailable: yes
        gpgcheck: yes
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/mrmeee/ansible-awx/pubkey.gpg
        repo_gpgcheck: no
        
    - name: Add RABBITMQ repository
      yum_repository:
        name: bintray-rabbitmq-rpm
        file: rabbitmq
        description: bintray-rabbitmq-rpm
        baseurl: https://dl.bintray.com/rabbitmq/rpm/rabbitmq-server/v3.7.x/el/7/
        gpgcheck: no
        repo_gpgcheck: no
        enabled: yes

    - name: Add RABBITMQ ERLANG repository
      yum_repository:
        name: bintray-rabbitmq-erlang-rpm
        file: rabbitmq-erlang
        description: bintray-rabbitmq-rpm
        baseurl: https://dl.bintray.com/rabbitmq-erlang/rpm/erlang/21/el/7/
        gpgcheck: no
        repo_gpgcheck: no
        enabled: yes
 
    - name: Install RabbitMQ
      yum: name=rabbitmq-server

    - name: Install GIT
      yum: name=rh-git29

    - name: Install PostgreSQL
      yum: name=rh-postgresql10
      
    - name: Install Memcached
      yum: name=memcached
      
    - name: Install NGINX
      yum: name=nginx
      
    - name: Install PYTHON36
      yum: name=rh-python36
      

    - name: Install PYTHON36-SPECIAL
      yum:
        name: rh-python36*
        disablerepo: *
        enablerepo: copr:copr.fedorainfracloud.org:mrmeee:ansible-awx, base
        exclude: *-debuginfo
        
    - name: Install AWX
      yum: name=ansible-awx